apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgAxdOwB1aE5l0ACMEnTYYPK6r8xK/kp81BkBeX8gqoVgU+MIQWUT7+CWA44WUowAJTUDqO72Kv6sz8vO3oLeOON/ryKsJbkhcSeNipgDzxFNqJlFKiY2JeS8bdyl+0yp3aRqgY67mhk3TP05Ckw3122QHv06/EHdIOnzi9AMa/+60laCOF4LiKQ8JpZ7PNgDJXI8b1/T8r6rnCdZEpIf86j/UeAZ9eofqDPEJb8YIx1CEcpJePwrhBrGeKZrN9tLZXDEIczuDMqOspEgU8q9H+Vywlh7hg68Bui3h/lfcNiCUqoEyUTgS/k3PIUUGodj2O9pDXjLLDiYjBkzKY0TPONtFFRGY/nBLhfMG29hCxMsnED2zVZ29fuVO/N9bHQzodRwj5UuTskvedleXGgdaFX7ehIrbpTmFp4iR+/S57iW6N83/KP6VMRC1cqK/YUo3N/Cz9vC+DvBjd8hUKKj0zapAUA37bBySq712ajc8OFuAZ+0RnTgR5ze5jg27lSeRK73nbNmQiQYglUDOY+sVvRxX7zAGl2NhWX15UIHt3/bZNI7PE+6+xeX45MnR5wnkB63rOX0gNGFsGXczc/P3qjQyqToYeBPv9e41ZDElt7A1spQwJk4zoJRbJ1Bd/lmxsp/hCRlZ1VjqfEIQUCw1xnIwsWT4J/N3NiIgyOjG7zYtpNVCkglFt3B21EZWbTgehjHrMizEcFvQ==
    DB_USER: AgB+ndnPGiWEgZTiWXUHTs5DoWCKiMdKVTkINQaiGQtM+RATVUf/pLxQLW/BJ3JLeq35k8ZZYwcn5dQhioWakdBUClTYZyEwM2JxhPnD9WNAijYDpQrz9gkULYlUVTNMFOh9LnWOMHDq3QjghzRQCAsrZ9h5jOpiCzxnkYyaHxlFZkywjiYHwiUNWF5kHuV7J9T8TEkEBF02nrTjElsGhwujur65h/GIb0k3g1yWjFKkcqDust30RrJr3kvtMKBsXalB8wC7X52ESNoViFYw9tXY5D9u7lI/a7iC93KIjEkAROQezHHF5+ut5eSrOFrDSKfE/BkPgIdUKOW745YwhO2qagnoz3S1fPsNQcFs1ny5cHkrgPKcfghE0bCD61cOPpW8fK7KvUTuF+VIerAVwx4ZT5pHcfPL5KYldxgEQoZR9qpmOO8eUXb3eHuc4pHp+il2amykdaPmiTrgGOTIiXMhpGs2s0MiLBIzo5QynZJYM6P2NSL91MR15mMSH3rHgnieAxTTyp7vuy8rHmxah2EsJKmBbrtx8gA4SZzlB/5Dy04T8A6z5/BOf9hgbtnGDlQlSCmHho2CcrmzwakoVKxDwWA6QD9YYFR3BcUVjX8GsOW3T/YoFxWFnDOSIdGEvbNflgd2SANTTBwrbU33LyXiVYk4dyYu0t/JaJDhYHOuoAWsbCPtz5F8wfHtIFWsKWynfmn3s3Fygw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

