apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgAJ8RUtkFH//jQXj7y8nJ191YCVSiD6aRUXZ6ioZOK0xJ+foeD06Rjxhpw5F/9afrCSECltfUXtj6USJTuPy2d5I6rAM4ASb7xf4sLrRrIdMLbTr1EMUQPNfV4C+gUasZ4Kd+M9uyTIpAAiT9jL1xDGMGTzkxQseK1cOaa5nqSGPmeP7xbAzTqyX+hGNiISLtWve/JywNA0rILXtajnQqZyZKCel696C4QB4mhpCFCu1VSNZmb4yNa2FJ4ZI1tICk629rigNeZZuScIqHgrAjHF0aP10WYWCEUdeQoTKLsDJVrkDgSlYiSGIZCU52VQPrg9LEiupFurrulRI6IQsHr7dfM9jRvdwoNrIbNhwiBoJPtp8xV5vKQDMyx5yknreVBI3zoZPvxgIb7xaeXMa35kjAnc1LZYWmWPfh+evp70SFz8TcAcr5VKCcZE2oZzZNdT5Ug4ZUUUQm65YABWwDfogOV8AmJhfqXfB/8GO0lJfGL3vjYnGONtEMQ0CEOTNgItsUfKbp5prEK2gy9Ioh6QFtZi9DceHiz1hmFJuTebm/+kCoHC2+MEErvzjyv77VqSxGvSKLJ//AgJRg0xknQFjjOvr7uHAWvBdGYap7mcnRF/bGb8nZVV6pi8FvlAXEhdx2WC/oXL1xCpLSTcol5/xuoXUEGk2g8gPGwkdSaOpZbaj76HFxVdraMjUKXMdsrTUODYJyw5uQ==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

