apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgCbganBzJwsF+VRhukgp8fWtGZLpsDTZZVFMoZTd/kKDZnxUYa1fHs7UI0SDbca1ygt/sYisdJmPEdkx97AyOOhAY1DajP/FpHDZdsKw8tCjKEPnP+fRre+pJwYsv96sIeD2NnVuy7z0eZ4IQXCVQzFjiLj1PM1lCt12ci36KfTqt/CJWji+xJvYvaK3G8XUdgYJcDtrV1WouWnymIDZO8lhQ2VbL3bKAKFPUXPZPw8R2zXEHlekz7r+d2HB9a0mecLRkMxaVz6k6lBoaN8nMXnOFRFyPUu1iOcnkQeIO7RwioWc7AtFZazsq7Vmm7cYCikDWNemFR9upsBC/T93+kwANjsdA1p7nK+KIS8HtFSwAMXFbpXnLkF+wYDeMGBMBtF34V36S9PtCLEWF+Djm3epuCZHWKWFpzB6qeG+Vneaf1ukfStqUDmDx1ghJoa9wGE1lqUdbUSlLLdGVlkNDrl9RMtBq9woKc2e9aNBzQ8oa4leilEtJ1+6NEVEYGxTFI0bCE117y/n0mXbCt6SNrRzOcGdzJtB9fc2fLKNw6wtRnW9JJACfB49zAcBWhK4OjHbFo42AbCOaVD5OKnJq5LZcsFe2qL2FzbfszoIroGTBt/IRu7LIwEbfx6jD4xlDOMiXhxpKHhh5ql5Z30ke5IJqrIDtreeoPfGkGL2IVJJx4f2fdX6OgTDMwEvIGv5hdqkES3yszpxA==
    DB_USER: AgAooiFYXkA8r6n8OxcnJj6M2JU4gP2VnjGspSCIQIcKFe0dpOzBOsfehP4RVh4KjAnP/qXphoRVod9JLoLEbWA7hiANU5V3m2FoM9SWhyUoBptdN7ZLKxWQqGWlPK3fLoUxqRfArLqw9vAGm4IGp3ladhOLCb9KOuxpeJFe6CmE5li6Sds9TAV/eWDC59pK+P1Uxs1AJW4tgsubMRCSx+zT14FfU5gSjUg2s2yUq09duLtUV8fZAnuXD16BsXzdSfGukDOQHBhmYtdum5PKRmOwFUTottkz45gFNAo1ED7z8ERkoIO8pHP8Va0Nir9kx2QJnE6p4p7ErcONjSN/h6HZMvAo1zqrnOi0otr7M9i2aC90tr+a+jVNJoNui/fUTAdyu27yQt22cHHlWyJvyKHqPujlYUuHdmC7QohYYSMe2Ob0Eu7/fQx+46ssp3vCYg2u/u4hAfXAKTr4P+IWTKz+b3sEIhEQkZ/vjf6Pz+lpVCNaeDGbP0/ah14yqoJpBdHxxyE3+XgH+/1C6GHomL8Xqvz1K5Gvz4c4Mmq0BuhKendqKS1mFQrp2Hf2pNXyQc3zasRcgY6XMiszjfmLOOK86JJ1j6J1mb4/1DmEqf/MXVxw+gMIyQH0RJRhj7WmXPRRI/tteqeekNUDn3DcEhyVBAMri17KpxuVL6Izs4t+J80dbiRUFKV4GRlAb8xNehIMPUhvdkNycQ==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

