apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBvuoiXGHeW5lRBurHO0obYiTbRljKs6L24kvti7S8LuE5TAKPvCzi3gSsOEfjZorzG4oQCf9ygLT1E7vIBKwSGFhrb4GrrxBm5mLgHbTwsIe5l/kjBKWukZcCDhlz1UBsjIR8OYiVnqmFRIFaFgpTdOla5xdxbDpm0PciiTnor5JzD4so+4L665U/O5goA2W/38vC4GcpxrRKjIRZKTW11pzfl9YvdTnt+C8iJdL4inQWBDrSjccYc/2YCtWFCCInBZoKUrxrWkfiFFbyZn0KrBedPQ+7kIjouhOHa4rKVbAPTZ6pfLTxpcfoi5FwmRt4wUIWdp44dVBnyYeQ0xpD8Oiwce4RSpZZLEBpJabxNpCMRXPvRoUm9BhjvOOAKd+CxJoLfDP4hgTpkAkemjZhHbXgil1HSJitSpONt8NBIfXkPnpp4k60O8BJAXb2Fc708m80TdpXSSjGnp8UrX8nHn6Wx3BbJnVXzFn5vGnuO3Hy/XjlRSUyiD0TUv5rNwQCdgGUZCHWf7qytf0iy/7eyl8ku2Nmv9ca3TXxrayxmR/KXEJ3w/D1BDEuDEBtOVGdlAwC7lAAPl9uS//lZy06CWLK8DMqhOI3wXwzgLFxCXKDBvDcGZMGVABEVtg7NsaWlSm4EI2Bye3s3TibiDRErr4XMNF0Bwwd9UBvzVBCu1FIEmRqwT2kIAPkFa0ElQWn4k+5gzUEikA==
    DB_USER: AgBtiFQ6QSZJycisIGrv7d/hYztWO/TPUx2dMH3SlnBAQ1dPGno06xkW58mK1BVH7sn3wY5Z3PZs2/nbtYP9qMVKPBIkSo/d6BrN3wrDNyjW8kNpY0KJW0Rdk7xE1pR2ZaIAZGNwthb0lJ7OyNs+otrQgy2Q+UWenRzoemoOxt1Usl2dALVUHSfeuM/f87GJMITEe+0rcPQImbwrp80p1G6C+XRa2SzBGlMy9PF2LyFzwyf8or6pc9i4Fa2/tlMhCkeE6+xUlL3ZXN/fIsQhF1o4AWAGP6GQxx9tFxTMQoe4bbSuCjT/+ao+v9XRCPORsqxMrDffPQX4j8cs/+m12L+AZ8X+buY6dOEA8ZUdYoQx94He7/BnS1lTtQoCB5eWCw0E2W9XCawGpXrZTGPb6hq05nxD4Tw3RPuO/Xg0h4bEuQa1wQfo3reA76Rn4SoiPWA/WPHMiybYH/voA861o2HjUWo2BHKTYMnp7lhV2w8jXCAezb0AbumFbnGYFqRxhEyqDa/8ZjLmrW+k6h1VrddXBX0PQ0+m7p12jqRKGnj2RDFg9HiO95u9U6I2Q7kch9MNOgqyR03x7YdKZJJr41NtBX+I5mxfQLlf1W8q4kVca8pRyZecrZfJ9QPsot+62dTLz0QVEm+fSqh4DmF3UxTBSy/K370z+tO/6AUYaNxzV3aaGuyjX+L/t1Rj55e/2Z04eByJhmIOEw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

