kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: lwfw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lwfw
  template:
    metadata:
      labels:
        app: lwfw
    spec:
      containers:
        - name: lwfw
          image: image-registry.openshift-image-registry.svc:5000/b2bi-prod/lw-2.13@sha256:bc7fd389e96c1aaad87ffbe8c31002af65d9f120a2da39c917b6a9e2b0d3074c
          # command: [ "/bin/bash", "-c", "--" ]
          # args: [ "while true; do sleep 30; done;" ]
          ports:
            - name: lwfw
              containerPort: 5680
              protocol: TCP
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: lw-app-prop
            mountPath: /app/config
          - name: lw-data
            mountPath: /files
      volumes:
        - name: lw-app-prop
          projected:
            sources:
            - secret:
                name: lw-app-prop
            - configMap:
                name: lw-enc-jar
                items:
                  - key: LwEncryption.jar
                    path: LwEncryption.jar
                  - key: customer_LW_license.properties
                    path: customer_LW_license.properties
                  - key: application.properties
                    path: application.properties
        - name: lw-data
          persistentVolumeClaim:
            claimName: lwfw-files
  serviceName: lwfw